services:
  - type: web
    name: data-prep-back
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn run:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: MONGODB_URI
        sync: false
      - key: DEBUG
        value: "False"
